/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(estimator_fsk.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f2ad10bbeb5a3d0b9835e7a0813024a7)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <radar/estimator_fsk.h>
// pydoc.h is automatically generated in the build directory
#include <estimator_fsk_pydoc.h>

void bind_estimator_fsk(py::module& m)
{

    using estimator_fsk = ::gr::radar::estimator_fsk;


    py::class_<estimator_fsk, gr::block, gr::basic_block, std::shared_ptr<estimator_fsk>>(
        m, "estimator_fsk", D(estimator_fsk))

        .def(py::init(&estimator_fsk::make),
             py::arg("center_freq"),
             py::arg("delta_freq"),
             py::arg("push_power") = false,
             D(estimator_fsk, make))


        ;
}
