/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ofdm_divide_vcvc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6450dd1e4dd3f918cbeb0b41832f3ffb)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <radar/ofdm_divide_vcvc.h>
// pydoc.h is automatically generated in the build directory
#include <ofdm_divide_vcvc_pydoc.h>

void bind_ofdm_divide_vcvc(py::module& m)
{

    using ofdm_divide_vcvc = ::gr::radar::ofdm_divide_vcvc;


    py::class_<ofdm_divide_vcvc,
               gr::tagged_stream_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<ofdm_divide_vcvc>>(
        m, "ofdm_divide_vcvc", D(ofdm_divide_vcvc))

        .def(py::init(&ofdm_divide_vcvc::make),
             py::arg("vlen_in"),
             py::arg("vlen_out"),
             py::arg("discarded_carriers"),
             py::arg("num_sync_words"),
             py::arg("len_key") = "packet_len",
             D(ofdm_divide_vcvc, make))


        ;
}
