/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ts_fft_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(235e9875d778dc9ff2fb5ce01777060d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <radar/ts_fft_cc.h>
// pydoc.h is automatically generated in the build directory
#include <ts_fft_cc_pydoc.h>

void bind_ts_fft_cc(py::module& m)
{

    using ts_fft_cc = ::gr::radar::ts_fft_cc;


    py::class_<ts_fft_cc,
               gr::tagged_stream_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<ts_fft_cc>>(m, "ts_fft_cc", D(ts_fft_cc))

        .def(py::init(&ts_fft_cc::make),
             py::arg("packet_len"),
             py::arg("len_key") = "packet_len",
             D(ts_fft_cc, make))


        ;
}
